# Multistage build

# Build stage (as builder - alias)
FROM node:22-alpine as builder
# Define working dir
WORKDIR /app 
# Copy package files into workdir and run command
COPY package*.json ./
RUN npm ci
# Copy the rest files and run build
COPY . .
RUN npm run build

# Final stage
FROM node:22-alpine
# Define working dir
WORKDIR /app
# Copy dist files from builder
COPY --from=builder /app/dist ./dist